### ISSUE TITLE
redirect to

### ISSUE THREAD

**Issue by KalleBlomquist** [undx/redmine_redirect_to_after_login#1]
Hi i cant find any mail adress or something else in the net so i try it this way. I tried your plugin for redmine. But in the settings i cant find the field to define the URL. I use redmine 1.2.1 and in the pugins settings of redmine your plugin shows of correctly. What could be the problem here?

regards
clemens

**Comment by KalleBlomquist** [comment]
Ok. Sorry for that stupid question. I was looking in the settings of redmine. Now i found the settings button in the plugin list ;).

Thanks for this plugin it works well.

**Comment by undx** [comment]
Sorry, just saw your message now ! Happy it works fine for you !
