### ISSUE TITLE
Redmine 2.1.2 - "Missing template, responding with 404" Error Message

### ISSUE THREAD

**Issue by a-herbe** [undx/redmine_redirect_to_after_login#2]
Hi,

First, thanks for your job and time spent.

Like a lot of plugins, in 2.1.x release of Redmine, despite of loadind, whan accessing plugin configuration page, we've this error message :

Started GET "/settings/plugin/redirect_to_after_login" for 127.0.0.1 at 2012-10-18 19:27:06 +0200
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redirect_to_after_login"}
  Current user: a-herbe (id=3)
  Rendered plugins/redmine_banner/app/views/settings/plugin.html.erb within layouts/admin (15.6ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_project_body_bottom.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_body_bottom.html.erb (0.0ms)
  Rendered plugins/redmine_banner/app/views/banner/_after_top_menu.html.erb (0.0ms)
Completed 404 Not Found in 125ms (Views: 109.4ms | ActiveRecord: 0.0ms)

Otherwise, the plugin works in 2.1.x but no configurations possible.

Thanks for your answer to patch or fix plugin qeekly.

**Comment by undx** [comment]
Hello a-herbe,

i fixed the issue, it works now with latest 2.1-stable version.
Please, read installation section of the README.

Regards.

E.

**Comment by a-herbe** [comment]
Yes.

Great and quick fix.

I saw your commits (Suppress of attribute "for" of label anchor, change of extension type) and i'll test it on others plugins seems to don't work for the same reasons (I'll hope).

Thanks again.

**Comment by cedricbix** [comment]
Hello Undx,

I've just install your plug-in and restart Redmine.
And when I go to "Admin > Plug-in > "setup" of "redirect to" I get a 404 message.

Could you help me to make it works, please ?

For information, this is the content of Plug-ins dir :
/opt/bitnami/apps/redmine/htdocs/lib/plugins$ ls
acts_as_activity_provider  acts_as_list        acts_as_watchable        rfpdf
acts_as_attachable         acts_as_searchable  gravatar
acts_as_customizable       acts_as_tree        open_id_authentication
acts_as_event              acts_as_versioned   redirect_to_after_login

and content of "redirect_to_after_login"
/opt/bitnami/apps/redmine/htdocs/lib/plugins/redirect_to_after_login$ ls
app  init.rb  README.md

Thanks,

Cédric

**Comment by undx** [comment]
Hello Cédric.
Which version of Redmine are you running ?
Any message in log ?

br
