### ISSUE TITLE
redmine 2.2.3

### ISSUE THREAD

**Issue by markedagain** [undx/redmine_redirect_to_after_login#3]
had to remove module Hooks from ini.rb to get it to work

**Comment by westche** [comment]
what exactly did you delete to get this to work - I am having the same problem ...

**Comment by markedagain** [comment]
i forked and made the changes to show what i did
https://github.com/markedagain/redmine_redirect_to_after_login/blob/master/init.rb
notice i removed module Hooks and the closing "end" to it

**Comment by westche** [comment]
Great thanks!!

sent from moto x

**Comment by undx** [comment]
hi ! 
thanks for the update...
A pull request ?
regards.

**Comment by markedagain** [comment]
@undx i did not want to make a pull request, because im unsure if this only affects new versions of ruby or not. We would need to run tests and maybe have a version check before loading the hooks
